name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
          token: ${{ secrets.GITHUB_TOKEN }}
